name: onPush
on: [push, pull_request]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
